pipeline
{
    agent any
    triggers
    {
    pollSCM '* * * * *'
    }

    tools
	{
	  maven 'MAVEN_HOME'
	  jdk 'JAVA_HOME'
	}
    stages
	{
          stage ('Compile Stage')
	   {
             steps 
		{
                  bat 'mvn -f "springdocker//pom.xml" clean compile'
		}
           }
           stage ('Testing Stage')
	   {
             steps 
		{
                  bat 'mvn -f "springdocker//pom.xml" test'
		}
           }
           stage ('Install Stage')
	   {
             steps 
		{
                  bat 'mvn -f "springdocker//pom.xml" install'
		}
           }
	  
	  stage('build and push docker image')
          {
            steps
    	      {
      		 script
      		 {
     		  def customImage = docker.build("prashakha12/springboot-image")
      		  customImage.push()
                 }
              }
          }
         stage('run docker image')
          {
            steps
    	      {
                script
      		 {
      		  docker.image('prashakha12/springboot-image').withRun("-p 9222:9222")
                  {
                    sh label: 'running image'
                  }
      	        } 
              }
          }
	}	
}